import type { StatusCode, StatusDef } from "@/lib/taxonomy/types";

/**
 * Status taxonomy — data, not if-chains.
 * Matchers are matched case-insensitively after light normalization.
 */
export const STATUS_DEFS: StatusDef[] = [
  {
    code: "CASE_RECEIVED",
    stage: "RECEIVED",
    severity: "info",
    isTerminal: false,
    decisionOutcome: null,
    explanationSlug: "case_was_received",
    matchers: [
      "Case Was Received",
      "Case Was Received And A Receipt Notice Was Sent",
      "Case Was Received And A Receipt Notice Was Sent Electronically",
    ],
    allowedNext: [
      "FEE_RECEIVED",
      "BIOMETRICS_SCHEDULED",
      "ACTIVELY_REVIEWING",
      "RFE_SENT",
      "CASE_TRANSFERRED",
      "APPROVED",
      "DENIED",
    ],
  },
  {
    code: "FEE_RECEIVED",
    stage: "RECEIVED",
    severity: "info",
    isTerminal: false,
    decisionOutcome: null,
    explanationSlug: "fingerprint_fee_was_received",
    matchers: ["Fingerprint Fee Was Received"],
    allowedNext: ["BIOMETRICS_SCHEDULED", "BIOMETRICS_TAKEN", "ACTIVELY_REVIEWING"],
  },
  {
    code: "BIOMETRICS_SCHEDULED",
    stage: "BIOMETRICS",
    severity: "info",
    isTerminal: false,
    decisionOutcome: null,
    explanationSlug: "biometrics_appointment_was_scheduled",
    matchers: [
      "Biometrics Appointment Was Scheduled",
      "Fingerprint Appointment Was Scheduled",
    ],
    allowedNext: ["BIOMETRICS_TAKEN", "ACTIVELY_REVIEWING"],
  },
  {
    code: "BIOMETRICS_TAKEN",
    stage: "BIOMETRICS",
    severity: "info",
    isTerminal: false,
    decisionOutcome: null,
    explanationSlug: "fingerprints_were_taken",
    matchers: [
      "Case Was Updated To Show Fingerprints Were Taken",
      "Fingerprint Review Was Completed",
    ],
    allowedNext: ["ACTIVELY_REVIEWING", "RFE_SENT", "INTERVIEW_SCHEDULED"],
  },
  {
    code: "ACTIVELY_REVIEWING",
    stage: "REVIEW",
    severity: "info",
    isTerminal: false,
    decisionOutcome: null,
    explanationSlug: "case_is_being_actively_reviewed",
    matchers: [
      "Case Is Being Actively Reviewed By USCIS",
      "Case Is Currently Being Reviewed",
    ],
    allowedNext: [
      "RFE_SENT",
      "NOID_SENT",
      "INTERVIEW_SCHEDULED",
      "APPROVED",
      "DENIED",
      "CASE_TRANSFERRED",
    ],
  },
  {
    code: "RFE_SENT",
    stage: "EVIDENCE_REQUESTED",
    severity: "action_required",
    isTerminal: false,
    decisionOutcome: null,
    explanationSlug: "request_for_evidence_was_sent",
    matchers: [
      "Request for Additional Evidence Was Sent",
      "Request For Evidence Was Sent",
    ],
    allowedNext: ["RFE_RESPONSE_RECEIVED", "ACTIVELY_REVIEWING", "DENIED"],
  },
  {
    code: "NOID_SENT",
    stage: "EVIDENCE_REQUESTED",
    severity: "action_required",
    isTerminal: false,
    decisionOutcome: null,
    explanationSlug: "request_for_evidence_was_sent",
    matchers: ["Notice Of Intent To Deny Was Sent"],
    allowedNext: ["RFE_RESPONSE_RECEIVED", "ACTIVELY_REVIEWING", "DENIED"],
  },
  {
    code: "RFE_RESPONSE_RECEIVED",
    stage: "REVIEW",
    severity: "info",
    isTerminal: false,
    decisionOutcome: null,
    explanationSlug: "response_to_rfe_was_received",
    matchers: [
      "Response To Request For Evidence Was Received",
      "Response To Notice Of Intent To Deny Was Received",
    ],
    allowedNext: ["ACTIVELY_REVIEWING", "APPROVED", "DENIED", "INTERVIEW_SCHEDULED"],
  },
  {
    code: "INTERVIEW_SCHEDULED",
    stage: "INTERVIEW",
    severity: "attention",
    isTerminal: false,
    decisionOutcome: null,
    explanationSlug: "interview_was_scheduled",
    matchers: ["Interview Was Scheduled"],
    allowedNext: ["INTERVIEW_COMPLETE", "APPROVED", "DENIED"],
  },
  {
    code: "INTERVIEW_COMPLETE",
    stage: "INTERVIEW",
    severity: "info",
    isTerminal: false,
    decisionOutcome: null,
    explanationSlug: "interview_was_completed",
    matchers: ["Interview Was Completed"],
    allowedNext: ["ACTIVELY_REVIEWING", "APPROVED", "DENIED", "OATH_SCHEDULED"],
  },
  {
    code: "OATH_SCHEDULED",
    stage: "POST_DECISION",
    severity: "positive",
    isTerminal: false,
    decisionOutcome: null,
    explanationSlug: "oath_ceremony",
    matchers: [
      "Oath Ceremony Will Be Scheduled",
      "Oath Ceremony Notice Was Mailed",
    ],
    allowedNext: ["APPROVED", "CARD_IN_PRODUCTION"],
  },
  {
    code: "CASE_TRANSFERRED",
    stage: "REVIEW",
    severity: "info",
    isTerminal: false,
    decisionOutcome: null,
    explanationSlug: "case_was_transferred",
    matchers: ["Case Was Transferred And A New Office Has Jurisdiction"],
    allowedNext: ["ACTIVELY_REVIEWING", "RFE_SENT", "APPROVED", "DENIED"],
  },
  {
    code: "APPROVED",
    stage: "TERMINAL",
    severity: "positive",
    isTerminal: true,
    decisionOutcome: "APPROVED",
    explanationSlug: "case_was_approved",
    matchers: [
      "Case Was Approved",
      "Case Approval Was Affirmed",
      "Case Was Approved And My Decision Was Emailed",
    ],
    allowedNext: ["CARD_IN_PRODUCTION", "CARD_MAILED", "OATH_SCHEDULED"],
  },
  {
    code: "DENIED",
    stage: "TERMINAL",
    severity: "negative",
    isTerminal: true,
    decisionOutcome: "DENIED",
    explanationSlug: "case_was_denied",
    matchers: ["Case Was Denied"],
    allowedNext: [],
  },
  {
    code: "CARD_IN_PRODUCTION",
    stage: "POST_DECISION",
    severity: "positive",
    isTerminal: false,
    decisionOutcome: null,
    explanationSlug: "new_card_is_being_produced",
    matchers: ["New Card Is Being Produced"],
    allowedNext: ["CARD_MAILED", "CARD_DELIVERED"],
  },
  {
    code: "CARD_MAILED",
    stage: "POST_DECISION",
    severity: "positive",
    isTerminal: false,
    decisionOutcome: null,
    explanationSlug: "card_was_mailed",
    matchers: ["Card Was Mailed To Me", "Document Was Mailed"],
    allowedNext: ["CARD_DELIVERED"],
  },
  {
    code: "CARD_DELIVERED",
    stage: "TERMINAL",
    severity: "positive",
    isTerminal: true,
    decisionOutcome: "APPROVED",
    explanationSlug: "card_was_mailed",
    matchers: ["Card Was Delivered To Me By The Post Office"],
    allowedNext: [],
  },
  {
    code: "UNKNOWN",
    stage: "UNKNOWN",
    severity: "info",
    isTerminal: false,
    decisionOutcome: null,
    explanationSlug: "unknown",
    matchers: [],
    allowedNext: [],
  },
];

export const STATUS_BY_CODE: Record<StatusCode, StatusDef> = STATUS_DEFS.reduce(
  (acc, def) => {
    acc[def.code] = def;
    return acc;
  },
  {} as Record<StatusCode, StatusDef>,
);
